### ISSUE TITLE
Семантика

### ISSUE THREAD

**Issue by MorganaLF** [RomKmeister/resume#11]
А почему здесь используется `<article>`? 

https://developer.mozilla.org/ru/docs/Web/HTML/Element/article

> HTML-элемент `<article>` представляет самостоятельную часть документа, страницы, приложения или сайта, предназначенную для независимого распространения или повторного использования. Этот элемент может представлять статью на форуме, статью в журнале или газете, запись в блоге или какой-либо другой самостоятельный фрагмент содержимого.

![Снимок экрана от 2020-02-27 20-46-25](https://user-images.githubusercontent.com/38564412/75471299-1b40e300-59a3-11ea-8d6e-066147abb9b6.png)

**Comment by RomKmeister** [comment]
Мне показалось, что здесь можно использовать article, так как он содержит резюме целиком, получается осмысленный независимый блок. Например, не статья в газету, но в качестве примера работ в бумажном портфолио.

**Comment by MorganaLF** [comment]
Ну не знаю, я бы тут не согласилась, вот еще например о том, что в таком случае article избыточен:

> When the main content of the page (i.e. excluding footers, headers, navigation blocks, and sidebars) is all one single self-contained composition, that content may be marked with an article, but it is technically redundant in that case (since it's self-evident that the page is a single composition, as it is a single document).

https://html.spec.whatwg.org/multipage/sections.html#the-article-element

Плюс ко всему валидатор (https://validator.w3.org/nu/#textarea) варнинг показывает, что в article должен быть заголовок

![Снимок экрана от 2020-03-05 10-54-40](https://user-images.githubusercontent.com/38564412/75959720-ce439c00-5ecf-11ea-9ea8-d051c6b6ad48.png)

Из https://developer.mozilla.org/ru/docs/Web/HTML/Element/article

![Снимок экрана от 2020-03-05 10-57-26](https://user-images.githubusercontent.com/38564412/75959871-2084bd00-5ed0-11ea-8cb3-d862cf0fafa8.png)

В общем, я думаю, тут все же не совсем корректное использование
