### ISSUE TITLE
Perfect pixel

### ISSUE THREAD

**Issue by MorganaLF** [RomKmeister/resume#16]
Нужно добавить в корень проекта изображение, которое использовалось для perfect pixel (в том же размере), и скрин с настройками perfect pixel

**Comment by MorganaLF** [comment]
А что за NAME HERE в самом низу? Такое разве было в макете?)

![Снимок экрана от 2020-02-27 22-22-58](https://user-images.githubusercontent.com/38564412/75478926-cb1c4d80-59af-11ea-9687-f8ede804e8ef.png)

**Comment by RomKmeister** [comment]
Добавил. У меня в макете почему-то был второй заголовок. Если его не должно быть может убрать?
И еще сразу по perfect pixel, я исходил из того, в заголовках расстояния от иконки до текста везде должно быть одинаковым. А то что, немного не по центру, надо центрировать.

**Comment by MorganaLF** [comment]
> И еще сразу по perfect pixel, я исходил из того, в заголовках расстояния от иконки до текста везде должно быть одинаковым. А то что, немного не по центру, надо центрировать.

Да, если есть какие-то очевидные косяки в макете, то предпочтительнее пойти простым путем и отцентрировать / сделать одинаковым и т.п., а не городить костыли ради перфект пикселя

**Comment by MorganaLF** [comment]
> У меня в макете почему-то был второй заголовок. Если его не должно быть может убрать?

Скинула в личку psd макет на всякий случай

**Comment by MorganaLF** [comment]
Что-то в левой колонке внизу всё поплыло 

![Снимок экрана от 2020-03-11 22-30-12](https://user-images.githubusercontent.com/38564412/76456436-096e2f80-63e8-11ea-95c4-387a6c879ae8.png)
