### ISSUE TITLE
Стандарты

### ISSUE THREAD

**Issue by MorganaLF** [RomKmeister/resume#4]
В проекте сейчас подключен favicon, но нет поддержки различных платформ. О том, как правильно подключить favicon, описано здесь: https://github.com/fullstack-development/front-end-best-practices/blob/master/HTML/includeFiles.md

**Comment by MorganaLF** [comment]
https://github.com/fullstack-development/front-end-best-practices/blob/master/JS/goodPractice.md

> В случае, когда параметры передаются объектом, получать их значения предпочтительнее с помощью деструктуризации;

Эту же рекомендацию можно применить и к pug

![Снимок экрана от 2020-02-27 21-27-16](https://user-images.githubusercontent.com/38564412/75474613-57c30d80-59a8-11ea-9587-cdb6f49dd7eb.png)

**Comment by RomKmeister** [comment]
А как лучше написать деструктуризацию? Так
![1](https://user-images.githubusercontent.com/46928144/75616405-7fa9a100-5b61-11ea-9070-c26b064f0c9b.jpg)
или так
![2](https://user-images.githubusercontent.com/46928144/75616407-8afccc80-5b61-11ea-8800-4c0f9f888736.jpg)

**Comment by MorganaLF** [comment]
> А как лучше написать деструктуризацию?

В обучающем задании, я думаю, не сильно принципиально, но на реальных проектах первый вариант удобнее, поэтому лучше сразу привыкать к нему.

**Comment by MorganaLF** [comment]
Еще небольшое замечание по стандартам: что в pug лучше соблюдать те же рекомендации, что и для js: не пропускать точки с запятыми, ставить пробелы в фигурных скобках и т.п.

![Снимок экрана от 2020-03-05 23-27-45](https://user-images.githubusercontent.com/38564412/76022830-f4e9ed00-5f38-11ea-8915-1c506f77db8a.png)
